name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependências
        run: npm install --prefix back

      - name: Rodar testes
        run: npm test --prefix back

      - name: Copiar arquivos para a EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "back/**"
          target: "/home/ubuntu/supermarket-stock/back"

      - name: Reiniciar PM2 na EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/supermarket-stock/back
            npm install
            pm2 start server.js --name "supermarket-api" || pm2 restart supermarket-api
            pm2 save
