# Usar uma imagem oficial do Node.js
FROM node:18-alpine

# Definir o diretório de trabalho dentro do container
WORKDIR /app

# Copiar os arquivos de dependências primeiro (para otimizar cache)
COPY package*.json ./

# Instalar as dependências
RUN npm install

# Copiar o restante dos arquivos do projeto
COPY . .

# Expor a porta usada pela aplicação
EXPOSE 3000

# Definir a variável de ambiente e iniciar a aplicação
CMD ["npx", "cross-env", "NODE_ENV=production", "node", "server.js"]